### ISSUE TITLE
Suggestion:  change title color

### ISSUE THREAD

**Issue by MadhuS-05** [MadhuS-05/github-cc-apr25#1]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
h1 {
  color: #c5871b;
}
```
